// src/App.tsx
import styles from "./App.module.css";

function App() {
  return (
    <main className={styles.main}>
      <div className={styles.left}>
        <section className={styles.sidebarTop}>
          <img
            className={styles.avatar}
            aria-hidden
            alt=""
            src="/foto.webp"
          ></img>
          <h1 className={styles.name}>Jor Sanders</h1>
          <p className={styles.title}>Web developer</p>
        </section>

        <section className={styles.sidebarBlock}>
          <h2 className={styles.sidebarHeading}>Contact</h2>
          <p className={styles.contactLine}>
            <a className={styles.link} href="tel:+31622725596">
              +31 6 22 72 55 96
            </a>
          </p>
          <p className={styles.contactLine}>
            <a className={styles.link} href="mailto:me@jor.dev">
              me@jor.dev
            </a>
          </p>
          <p className={styles.contactLine}>
            <a className={styles.link} href="https://github.com/JorSanders/">
              github.com/JorSanders
            </a>
          </p>
          <p className={styles.contactLine}>
            <a
              className={styles.link}
              href="https://www.linkedin.com/in/jor-sanders/"
            >
              linkedin.com/in/jor-sanders
            </a>
          </p>
        </section>

        <section className={styles.sidebarBlock}>
          <h2 className={styles.sidebarHeading}>Skills</h2>
          <ul className={styles.skillsList}>
            <li className={styles.skillsItem}>TypeScript, Next.js, React</li>
            <li className={styles.skillsItem}>
              Java, Spring Boot, Ruby on Rails
            </li>
            <li className={styles.skillsItem}>
              OpenShift, Kubernetes, Kustomize, Docker Swarm
            </li>
            <li className={styles.skillsItem}>
              GitHub Actions, GitLab CI/CD, Tekton, Jenkins
            </li>
            <li className={styles.skillsItem}>MySQL, MSSQL</li>
          </ul>
        </section>
      </div>

      <div className={styles.right}>
        <section className={styles.contentBlock}>
          <h2 className={styles.contentHeading}>Personal Summary</h2>
          <p className={styles.body}>
            A team-oriented developer, always available to help with or answer
            any questions. I also love diving into complex problems and finding
            a practical solution for our team to use.
          </p>
        </section>

        <section className={styles.contentBlock}>
          <h2 className={styles.contentHeading}>Experience</h2>
          <ol className={styles.experienceList}>
            <li className={styles.experienceItem}>
              <p className={styles.roleLine}>
                Frontend developer & DevOps | NOS (8/2022 - current).
              </p>
              <p className={styles.body}>
                At NOS I am part of the frontend team that works on the main
                website{" "}
                <a className={styles.link} href="https://nos.nl">
                  nos.nl
                </a>
                . This team converts the designs and backend endpoints into a
                functional, accessible and awesome website. For this team I am
                responsible for the CI/CD setup, such as OpenShift deployments
                and pipelines.
              </p>
            </li>
            <li className={styles.experienceItem}>
              <p className={styles.roleLine}>
                Backend developer | Capgemini (11/2019 - 5/2022).
              </p>
              <p className={styles.body}>
                I worked on DigiD for Logius, which is one of Capgemini&apos;s
                customers. Here I worked on a variety of items such as
                containerizing, splitting the monolith application into
                microservices, and connecting to eIDAS (European electronic
                identification).
              </p>
            </li>
            <li className={styles.experienceItem}>
              <p className={styles.roleLine}>
                Backend developer | Perfect Web Team (2/2017 - 8/2019).
              </p>
              <p className={styles.body}>
                During my studies I worked as a part-time backend developer. The
                work mostly consisted of making custom Joomla! components using
                PHP, jQuery, and MySQL. As my graduation internship I set up a
                CI/CD environment for Perfect Web Team.
              </p>
            </li>
          </ol>
        </section>

        <section className={styles.contentBlock}>
          <h2 className={styles.contentHeading}>Education</h2>
          <p className={styles.roleLine}>
            HBO-ICT | Windesheim Flevoland (8/2015 - 6/2019).
          </p>
          <p className={styles.body}>
            During the first year of my bachelor&apos;s we learned a foundation
            of IT skills. From the second year onwards we got to apply that
            knowledge at internships. I have done five internships, each
            spanning half a year, which gave me a lot of experience working with
            different technologies, companies, and people. My minor, as part of
            this bachelor&apos;s, I chose to do abroad, studying for half a year
            at Wenzhou University in China.
          </p>
        </section>
      </div>
    </main>
  );
}

export default App;

// src/app/app.component.ts
import { Component } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'resume';
  constructor(private translate: TranslateService) {
    translate.setDefaultLang('nl');
    translate.use('nl')
  }
  useLanguage(language: string): void {
    this.translate.use(language);
  }
}

<div class="main-container">
  <article class="container">
    <section id="header">
      <div id="header-txt">
        <h1>Jor Sanders</h1>
        <h2 class="subheading primary-color">Web-, and Backend Developer</h2>
        <div id="contact-info">
          <div class="contact-item">
            <img class="icon" src="assets/mail.svg" alt="" />
            <a href="mailto:contact@jor.dev" target="_blank" rel="noopener noreferrer">contact@jor.dev</a>
          </div>

          <div class="contact-item ">
            <img class="icon" src="assets/phone.svg" alt="" />
            <span class="print-hidden">+31-6-xxxxxxxx
              <!-- Masked my phone number here to make bots not scan my phone number too easily. If you found my phone number in source or print layout, you deserve it-->
            </span>
            <span class="print-only">
              +31-6-22725596
            </span>
          </div>

          <div class="contact-item">
            <img class="icon" id="location" src="assets/location.svg" alt="" />
            Amsterdam
          </div>

          <div class="contact-item">
            <img class="icon" src="assets/web.svg" alt="" />
            <a href="https://jor.dev" target="_blank" rel="noopener noreferrer">jor.dev</a>
          </div>

          <div class="contact-item">
            <img class="icon" src="assets/linkedin.svg" alt="" />
            <span class="print-hidden">
              <a href="https://www.linkedin.com/in/jor-sanders/" target="_blank" rel="noopener noreferrer">LinkedIn</a>
            </span>
            <span class="print-only">
              LinkedIn.com/in/jor-sanders
            </span>
          </div>

          <div class="contact-item">
            <img class="icon" src="assets/github.svg" alt="" />
            <span class="print-hidden">
              <a href="https://github.com/jorsanders" target="_blank" rel="noopener noreferrer">Github</a>
            </span>

            <span class="print-only">
              Github.com/JorSanders
            </span>
          </div>
        </div>
      </div>
      <img id="header-picture" src="assets/profile.png" alt="Picture Jor" />
    </section>

    <div id="resume-content">
      <div id="resume-col-left">
        <section class="resume-item">
          <h2 class="resume-heading">Personal Summary</h2>
          <hr class="resume-heading-hr" />
          <p>I am a 25 year old software developer. Mainly specialized in back-end web development, besides back-end
            work I enjoy working on a wide range of subjects. One of the skills I take pride in is to be able to
            explain
            technical concepts in layman's terms. Because of this I have often been asked by colleagues to collaborate
            with them on a wide variety of items. E.g. Frontend, CI/CD automation, Database Administration, Linux
            Server
            Management and incident response. In this way I see myself as a real <b class="primary-color">team
              player</b> who is always ready to help others out.
          </p>
        </section>

        <section class="resume-item">
          <h2 class="resume-heading">Experience</h2>
          <hr class="resume-heading-hr" />
          <ul>
            <li><b>Capgemini</b> (11/2019 - 5/2022). During this time I have worked as a backend developer on
              <b class="primary-color">DigiD</b> for <b>Logius</b>. This was my first experience at a Large Company. I
              noticed that fairly quickly I got the hang of it. And from asking questions transitioned to answering
              them. Started to gain more responsibilities and work on the more complex subjects. The thing I am most
              proud of is unofficially becoming the first point of contact from the Ops teams when they needed help
              from
              the development teams.
            </li>
            <li><b>Perfect Web Team</b> (2/2017 - 8/2019). In 2017 I started with an internship at Perfect Web Team.
              After
              this I started to work part-time during my studies as a backend developer, mostly during school
              holidays.
              In 2019 I did a second internship and after graduating I worked for another two months before looking
              for
              a new challenge.
            </li>
            <li><b>The Valley</b> (9/2018 - 1/2019). During this internship I worked in a Scrum team, together we
              re-designed and rebuilt the website <a href="https://www.fcutrecht.nl/" target="_blank"
                rel="noopener noreferrer">fcutrecht.nl</a>.</li>
            <li><b>Cinnovate</b> (9/2017 - 1/2018). In a team of interns we build a C# Library for <a
                href="https://www.pozyx.io/" target="_blank" rel="noopener noreferrer">Pozyx</a>. Pozyx is hardware
              used for indoor location tracking. Cinnovate used this indoor location tracking for some of their
              projects, mainly a self driving wheelchair.
            </li>
          </ul>
        </section>

        <section class="resume-item">
          <h2 class="resume-heading">Education</h2>
          <hr class="resume-heading-hr" />
          <p><b><span class="primary-color">HBO-ICT</span> at Windesheim Flevoland</b> (8/2015 - 6/2019) is where I
            graduated. During the first year of the study we learned a basis of IT skills. From the 2nd year onwards
            we
            got to apply that knowledge at internships. I have done 5 internships of each half a year. Which gave me a
            lot of experience working with different technologies, companies and people. During this study I have also
            done a Minor, I chose to do this abroad, studying for half a year at Wenzhou University in China.
          </p>
        </section>

      </div>

      <div id="resume-col-right">
        <section class="resume-item">
          <h2 class="resume-heading">Skills</h2>
          <hr class="resume-heading-hr" />
          <ul>
            <li><b>Java, <span class="primary-color">Spring Boot</span></b> Developed enterprise Applications</li>
            <li><b>C#, .NET Core, Umbraco</b> Developed enterprise Applications</li>
            <li><b>Ruby, Rails</b> Developed enterprise Applications</li>
            <li><b>PHP, Laravel, Joomla!</b> Developed enterprise Applications</li>
            <li><b>Javascript, TypeScript, Angular, Stencil, jQuery</b> Collaborated with Colleagues and some hobby
              projects</li>
            <li><b>Python, Bash, Go</b> Used for scripting</li>
            <li><b>C, C++</b> basic knowledge</li>
            <li><b>Gitlab CI/CD, Jenkins, Github workflows</b> Setup and further development of pipelines</li>
            <li><b>MySQL, MSSQL</b> Used in enterprise applications</li>
            <li><b>Docker, Docker-compose, Docker Swarm</b> Dockerized applications and hosted them swarm or compose
              stacks</li>
            <li><b>UML</b> Able to create and read UML models</li>
            <li><b>ELK</b> Basic understanding how ELK works and creating dashboards in Kibana</li>
          </ul>
        </section>

        <section class="resume-item">
          <h2 class="resume-heading">Languages</h2>
          <hr class="resume-heading-hr" />
          <ul>
            <li><b>Dutch</b> is my mother tongue</li>
            <li><b>English</b> I can speak and write fluently</li>
            <li><b>Chinese (mandarin)</b> honestly I only speak a little bit and can read even less</li>
          </ul>
        </section>

        <section class="resume-item">
          <h2 class="resume-heading">Interests</h2>
          <hr class="resume-heading-hr" />
          <p>After a day of work I enjoy playing games like Overwatch, Apex Legends or League of Legends. During
            weekends I enjoy having board game nights or going to bars.</p>
          <p>I would love to learn more about Kubernetes, Front-end development and pentesting. During my free time I
            often browse Reddit, Youtube or listen to Podcast to learn more about these and other technical subjects
          </p>
        </section>
      </div>
    </div>
  </article>
</div>
